### ISSUE TITLE
The set-url command's description seems innacurate

### ISSUE THREAD

**Issue by ezzatron** [jmalloc/grit#67]
The current help output:

```
$ grit help set-url
NAME:
   grit set-url - Set the URL for a Git remote and move the clone into the correct directory.

USAGE:
   grit set-url [command options] <slug | url> [<path>]

OPTIONS:
   --golang, -g  Move into the appropriate $GOPATH sub-directory.
```

Specifically this part:

> Set the URL for a Git remote

Seems to indicate that you can affect which remote has its URL changed. But there's no `--remote` option, and it always seems to affect the `origin` remote.

Don't get me wrong, 99% of the time I would want `origin` to be affected, but the description seems not to match the actual behaviour.

**Comment by jmalloc** [comment]
Turns out it prompts you if there is more than one remote configured. Otherwise, it just sets the URL for that one existing remote.

I'm not sure how useful this command really is. It's one that I tend to avoid using because I can never remember how it works. Probably what I really want is a "rename" command (ideally one that actually renames the repo remotely, which woudl require #57).
